name: redis_user_data_source
description: An implementation for our user data in Redis
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  user_data_source:
    path: ../user_data_source

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.12
  very_good_analysis: ^6.0.0
