name: user_data_source
description: An interface for our user data
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.12
  very_good_analysis: ^6.0.0
