name: strava_connection
description: Provides the Strava data source and options for manipulating this data.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  strava_client: ^2.1.3

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.12
  very_good_analysis: ^6.0.0
